[connections.snowflake]
account = "XZFRFSR-JB98989"
user = "DATAKO21"
password = "Test1234567"
role = "SYSADMIN"
warehouse = "COMPUTE_WH"
database = "SMOOTHIES"
schema = "PUBLIC"
client_session_keep_alive = true
